---

development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  API_HOST: https://showme-api.herokuapp.com

test:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  API_HOST: https://showme-api.herokuapp.com

app_test:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  API_HOST: http://localhost:9000
 

production:
  API_HOST: https://showme-api.herokuapp.com

  
