---
development:
  NEWS_API_KEY: <NEWS_API_KEY>
  SEC_API_KEY: <SEC_API_KEY>

test:
  NEWS_API_KEY: <NEWS_API_KEY>
  SEC_API_KEY: <SEC_API_KEY>
  
production:
  NEWS_API_KEY: <NEWS_API_KEY>
  SEC_API_KEY: <SEC_API_KEY>